<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<div class="container">
		<div class="col-lg-12">
			Isto é uma view - Index
			<hr>
			<span>Nome: </span> <?= $view_nome ?>
			<br>
			<span>Sobrenome: </span> <?= $view_sobrenome ?>
			<br>
			<span>Idade: </span> <?= $view_idade ?>
			<br>
			<span>Tamanho: </span> <?= $view_tamanho ?>
		</div>
	</div>
</body>
</html>
